### ISSUE TITLE
rev_B (from No-Face)

### ISSUE THREAD

**Issue by puneetjohal** [th0mazzz/Runaway#2]
While your aim is verbalized pretty clearly, a sketch or concept drawing of your ideas would've provided for an even clearer understanding of what your group is envisioning as your project's end goal. Having a sketch in your README was one of the parts of the assignment.

**Comment by LargeLlama** [comment]
We have a sketch prepared, just not in the README, it is in the docs directory. We will add it to the README so it is more clear. Thank you!
